### ISSUE TITLE
Reason for going from MIT to Unlicense?

### ISSUE THREAD

**Issue by paazmaya** [jslicense/spdx-license-ids#5]
I am just curious, what was the reason to make https://github.com/shinnn/spdx-license-ids/commit/2589d340c49f48ad7b0392d6a0779e1a3a098e05 happen?

I was about to request changing to MIT license from Unlicense, but instead opened this question...

**Comment by shinnn** [comment]
Just what the stacktrace.js maintainer said. https://github.com/stacktracejs/stackframe/issues/13#issuecomment-249558111

**Comment by paazmaya** [comment]
Thank you for the clarification

**Comment by BMillsVT** [comment]
Would you consider dual-licensing it under the MIT License and the Unlicense?  My company tries to steer clear of the Unlicense.

**Comment by shinnn** [comment]
Final conclusion: https://github.com/shinnn/spdx-license-ids/commit/99503b736664b79f6749aea4a5ec154a3ea73877

> Would you consider dual-licensing

No.

**Comment by BMillsVT** [comment]
@shinnn 

Thanks for the quick response.  I understand your point of view, but others have argued (and our lawyers at least agree enough to make it off limits) that the Unlicense causes more issues than it solves.  

[For example](http://softwareengineering.stackexchange.com/questions/147111/what-is-wrong-with-the-unlicense):
 
> **It's not global**. It doesn't make sense outside of a commonwealth ecosystem, is explicitly illegal in some places (Germany), and of unclear legality in others (Australia)
> 
> **It's inconsistent.** Some of the warranty terms cannot, logically, co-exist, given the current legal ecosystem, as written, with the licensing terms.
> 
> **Its applicability is unpredictable.** The license is short, clearly expressing intent, at the cost of not carefully addressing common license, copy-right and warranty issues. It leaves a lot of leeway interpretation - meaning that, in the US, it will take a few trials before you can reliably know when the license is applicable, and how.


Would you consider using the CC0 license?  Apparently that's "better" at being a public domain dedication since it has a better fall back clause. We'd really like to use your code. 

Also, if you're interested the OSI has a couple FAQs that talk about the issues associated with public domain dedications.   (https://opensource.org/faq#public-domain)

**Comment by shinnn** [comment]
Click the link in https://github.com/shinnn/spdx-license-ids/issues/5#issuecomment-269183284 and check it more carefully.

**Comment by BMillsVT** [comment]
Thanks!
